import type { Domain, DomainGroup, DomainId } from './types'

/**
 * Domínios observados. Nenhum é exclusivo do autismo: cada um declara o que
 * observa, seus limites e explicações alternativas para relatos frequentes.
 */
export const DOMAINS: Domain[] = [
  {
    id: 'social',
    code: 'EC-1',
    label: 'Interação social',
    short: 'Social',
    group: 'central',
    observes: 'Como você lê, acompanha e sustenta trocas com outras pessoas.',
    limits: 'Traços sociais variam muito com cultura, timidez, ansiedade social e experiências de vida. Relatos frequentes aqui não são específicos de autismo.',
    alternatives: ['ansiedade social', 'timidez', 'introversão', 'experiências de exclusão ou bullying', 'diferenças culturais'],
    basis: ['apa-dsm5tr', 'lai-2015', 'nice-cg142'],
  },
  {
    id: 'communication',
    code: 'EC-2',
    label: 'Comunicação',
    short: 'Comunicação',
    group: 'central',
    observes: 'Como você usa e interpreta linguagem, tom de voz, ironia e sinais não verbais.',
    limits: 'Pode refletir idioma, escolaridade, perda auditiva, estilo pessoal ou contexto de trabalho.',
    alternatives: ['diferenças de idioma', 'perda auditiva', 'transtornos de linguagem', 'ambiente com comunicação pouco clara'],
    basis: ['apa-dsm5tr', 'nice-cg142'],
  },
  {
    id: 'sensory',
    code: 'EC-3',
    label: 'Processamento sensorial',
    short: 'Sensorial',
    group: 'central',
    observes: 'Como sons, luzes, texturas, cheiros e toques afetam você.',
    limits: 'Sensibilidade sensorial também aparece em TDAH, enxaqueca, ansiedade, fadiga e outras condições.',
    alternatives: ['TDAH', 'enxaqueca', 'ansiedade', 'esgotamento', 'condições auditivas ou visuais'],
    basis: ['apa-dsm5tr', 'lai-2015'],
  },
  {
    id: 'repetitive',
    code: 'EC-4',
    label: 'Comportamentos repetitivos',
    short: 'Repetição',
    group: 'central',
    observes: 'Movimentos, falas ou ações que se repetem e costumam trazer conforto ou regulação.',
    limits: 'Hábitos repetitivos também ocorrem em TOC, tiques e sob estresse. A função do comportamento importa mais que a frequência.',
    alternatives: ['TOC', 'tiques', 'estresse', 'hábitos de concentração comuns'],
    basis: ['apa-dsm5tr'],
  },
  {
    id: 'routine',
    code: 'EC-5',
    label: 'Rotina e previsibilidade',
    short: 'Rotina',
    group: 'central',
    observes: 'Quanto mudanças, imprevistos e transições custam para você.',
    limits: 'Preferência por rotina é comum e pode aumentar com ansiedade, esgotamento ou excesso de demandas.',
    alternatives: ['ansiedade', 'esgotamento', 'excesso de demandas', 'preferência pessoal'],
    basis: ['apa-dsm5tr', 'nice-cg142'],
  },
  {
    id: 'interests',
    code: 'EC-6',
    label: 'Interesses intensos',
    short: 'Interesses',
    group: 'central',
    observes: 'Profundidade, duração e foco dos seus interesses.',
    limits: 'Interesses intensos são comuns e muitas vezes uma força. Sozinhos, não indicam nada.',
    alternatives: ['dedicação profissional ou acadêmica', 'hiperfoco associado ao TDAH', 'traço de personalidade'],
    basis: ['apa-dsm5tr'],
  },
  {
    id: 'masking',
    code: 'CX-1',
    label: 'Camuflagem social',
    short: 'Camuflagem',
    group: 'context',
    observes: 'Esforço para esconder ou compensar diferenças em situações sociais.',
    limits: 'As medidas de camuflagem ainda têm validade em discussão e podem refletir ansiedade social. Não entra no sinal de triagem; ajuda a interpretar.',
    alternatives: ['ansiedade social', 'exigências de ambientes profissionais', 'experiências de rejeição'],
    basis: ['hull-2019', 'lai-2015'],
  },
  {
    id: 'impact',
    code: 'CX-2',
    label: 'Impacto no dia a dia',
    short: 'Impacto',
    group: 'context',
    observes: 'Quanto as experiências descritas afetam trabalho, estudos, relações e energia.',
    limits: 'O impacto depende do ambiente, do apoio disponível e de outras condições de saúde.',
    alternatives: ['outras condições de saúde', 'sobrecarga no trabalho', 'falta de apoio'],
    basis: ['nice-cg142'],
  },
  {
    id: 'executive',
    code: 'AC-1',
    label: 'Funções executivas',
    short: 'Executivas',
    group: 'cooccurring',
    observes: 'Planejar, começar, organizar e acompanhar tarefas.',
    limits: 'Dificuldades executivas aparecem em TDAH, depressão, ansiedade, privação de sono e sobrecarga.',
    alternatives: ['TDAH', 'depressão', 'privação de sono', 'sobrecarga'],
    basis: ['lai-2019'],
  },
  {
    id: 'attention',
    code: 'AC-2',
    label: 'Atenção',
    short: 'Atenção',
    group: 'cooccurring',
    observes: 'Manter e direcionar o foco quando você precisa.',
    limits: 'A atenção oscila com sono, humor, ansiedade e ambiente.',
    alternatives: ['TDAH', 'ansiedade', 'sono insuficiente', 'ambiente com muitas interrupções'],
    basis: ['lai-2019'],
  },
  {
    id: 'anxiety',
    code: 'AC-3',
    label: 'Ansiedade',
    short: 'Ansiedade',
    group: 'cooccurring',
    observes: 'Preocupação, tensão e antecipação de que algo vai dar errado.',
    limits: 'Ansiedade é comum na população e pode ser reação a circunstâncias de vida.',
    alternatives: ['transtornos de ansiedade', 'estresse do momento', 'circunstâncias de vida'],
    basis: ['hollocks-2019', 'lai-2019'],
  },
  {
    id: 'mood',
    code: 'AC-4',
    label: 'Humor',
    short: 'Humor',
    group: 'cooccurring',
    observes: 'Tristeza persistente, perda de interesse e esgotamento.',
    limits: 'Estes itens não avaliam risco nem substituem conversa com profissional de saúde.',
    alternatives: ['depressão', 'luto', 'esgotamento', 'condições médicas'],
    basis: ['hollocks-2019', 'lai-2019'],
  },
  {
    id: 'sleep',
    code: 'AC-5',
    label: 'Sono',
    short: 'Sono',
    group: 'cooccurring',
    observes: 'Começar a dormir, manter o sono e acordar descansado(a).',
    limits: 'O sono é afetado por rotina, saúde, medicamentos, trabalho em turnos e ambiente.',
    alternatives: ['insônia', 'apneia', 'turnos de trabalho', 'medicamentos'],
    basis: ['lai-2019'],
  },
]

export const DOMAIN_BY_ID = Object.fromEntries(DOMAINS.map((d) => [d.id, d])) as Record<DomainId, Domain>

export const domainsIn = (group: DomainGroup) => DOMAINS.filter((d) => d.group === group)

export const GROUP_LABEL: Record<DomainGroup, string> = {
  central: 'Eixo central',
  context: 'Contexto',
  cooccurring: 'Áreas coocorrentes',
}

export const GROUP_DESCRIPTION: Record<DomainGroup, string> = {
  central: 'Seis domínios descritos na literatura sobre autismo em adultos. Formam o sinal de triagem.',
  context: 'Camuflagem e impacto no dia a dia. Ajudam a interpretar o sinal; o impacto também diferencia a faixa mais ampla.',
  cooccurring: 'Áreas que frequentemente aparecem junto. Cada uma tem indicador próprio e nunca se somam.',
}
