import type { Reference, ReferenceType } from './types'

/**
 * Biblioteca de referências. As fontes orientaram a organização dos domínios
 * e as regras do sistema; nenhum item foi copiado ou adaptado delas.
 * Antes de qualquer lançamento, a equipe deve verificar a vigência de cada
 * norma e registrar a data de acesso.
 */
export const REFERENCES: Reference[] = [
  {
    id: 'apa-dsm5tr',
    citation: 'American Psychiatric Association',
    title: 'Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR)',
    year: 2022,
    doi: '10.1176/appi.books.9780890425787',
    url: 'https://doi.org/10.1176/appi.books.9780890425787',
    types: ['conceitual', 'diretriz'],
    population: 'Classificação clínica geral.',
    limitations: 'Critérios para diagnóstico clínico, não para triagem. Descrição limitada de apresentações em adultos e em mulheres.',
    relation: 'Organização dos seis domínios do eixo central (EC-1 a EC-6).',
  },
  {
    id: 'nice-cg142',
    citation: 'National Institute for Health and Care Excellence',
    title: 'Autism spectrum disorder in adults: diagnosis and management (CG142)',
    year: 2021,
    url: 'https://www.nice.org.uk/guidance/cg142/chapter/recommendations',
    types: ['diretriz'],
    population: 'Adultos atendidos no sistema de saúde do Reino Unido.',
    limitations: 'Contexto assistencial britânico; recomendações precisam de adaptação ao Brasil.',
    relation: 'Distinção entre rastreio e avaliação diagnóstica; avaliação multiprofissional; impacto no dia a dia (CX-2).',
  },
  {
    id: 'baghdadli-2017',
    citation: 'Baghdadli, A.; Russet, F.; Mottron, L.',
    title: 'Measurement properties of screening and diagnostic tools for autism spectrum adults of mean normal intelligence: a systematic review',
    year: 2017,
    doi: '10.1016/j.eurpsy.2017.04.009',
    url: 'https://doi.org/10.1016/j.eurpsy.2017.04.009',
    types: ['revisao', 'validade', 'confiabilidade'],
    population: 'Adultos com inteligência na média.',
    limitations: 'Estudos incluídos com qualidade metodológica heterogênea.',
    relation: 'Justifica cautela: instrumentos de rastreio não devem ser usados como diagnóstico.',
  },
  {
    id: 'ehteshami-2023',
    citation: 'Ehteshami, S. et al.',
    title: 'Psychometric properties of Autism Spectrum Disorders screening tools: a systematic review',
    year: 2023,
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10744142/',
    types: ['revisao', 'validade'],
    population: 'Estudos de validação de instrumentos de rastreio.',
    limitations: 'Instrumentos e populações heterogêneos; poucos estudos brasileiros.',
    relation: 'Desenho do plano de validação científica.',
  },
  {
    id: 'who-autism',
    citation: 'World Health Organization',
    title: 'Autism — fact sheet',
    year: 2023,
    url: 'https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders',
    types: ['conceitual'],
    population: 'Visão global.',
    limitations: 'Texto informativo, não técnico.',
    relation: 'Linguagem de apresentação na página inicial.',
  },
  {
    id: 'lai-2015',
    citation: 'Lai, M.-C.; Baron-Cohen, S.',
    title: 'Identifying the lost generation of adults with autism spectrum conditions',
    year: 2015,
    doi: '10.1016/S2215-0366(15)00277-1',
    url: 'https://doi.org/10.1016/S2215-0366(15)00277-1',
    types: ['conceitual'],
    population: 'Adultos com diagnóstico tardio.',
    limitations: 'Revisão narrativa.',
    relation: 'Apresentações em adultos, diagnóstico tardio e camuflagem.',
  },
  {
    id: 'hull-2019',
    citation: 'Hull, L.; Mandy, W.; Lai, M.-C. et al.',
    title: 'Development and validation of the Camouflaging Autistic Traits Questionnaire (CAT-Q)',
    year: 2019,
    doi: '10.1007/s10803-018-3792-6',
    url: 'https://doi.org/10.1007/s10803-018-3792-6',
    types: ['validade', 'conceitual'],
    population: 'Adultos autistas e não autistas, amostra internacional.',
    limitations: 'Instrumento protegido; itens não reproduzidos aqui. Validade do construto ainda em discussão.',
    relation: 'Conceito de camuflagem social (CX-1).',
  },
  {
    id: 'baron-cohen-2001',
    citation: 'Baron-Cohen, S.; Wheelwright, S.; Skinner, R.; Martin, J.; Clubley, E.',
    title: 'The Autism-Spectrum Quotient (AQ): evidence from Asperger syndrome/high-functioning autism, males and females, scientists and mathematicians',
    year: 2001,
    doi: '10.1023/A:1005653411471',
    url: 'https://doi.org/10.1023/A:1005653411471',
    types: ['validade', 'conceitual'],
    population: 'Adultos no Reino Unido.',
    limitations: 'Instrumento protegido; itens não reproduzidos. Amostra original pouco diversa.',
    relation: 'Referência histórica de autorrelato em adultos.',
  },
  {
    id: 'lai-2019',
    citation: 'Lai, M.-C.; Kassee, C.; Besney, R. et al.',
    title: 'Prevalence of co-occurring mental health diagnoses in the autism population: a systematic review and meta-analysis',
    year: 2019,
    doi: '10.1016/S2215-0366(19)30289-5',
    url: 'https://doi.org/10.1016/S2215-0366(19)30289-5',
    types: ['revisao'],
    population: 'Pessoas autistas, estudos internacionais.',
    limitations: 'Alta heterogeneidade entre estudos.',
    relation: 'Seleção das áreas coocorrentes (AC-1 a AC-5).',
  },
  {
    id: 'hollocks-2019',
    citation: 'Hollocks, M. J.; Lerh, J. W.; Magiati, I.; Meiser-Stedman, R.; Brugha, T. S.',
    title: 'Anxiety and depression in adults with autism spectrum disorder: a systematic review and meta-analysis',
    year: 2019,
    doi: '10.1017/S0033291718002283',
    url: 'https://doi.org/10.1017/S0033291718002283',
    types: ['revisao'],
    population: 'Adultos autistas.',
    limitations: 'Instrumentos de medida variados entre estudos.',
    relation: 'Inclusão de ansiedade e humor como áreas coocorrentes.',
  },
  {
    id: 'kenny-2016',
    citation: 'Kenny, L.; Hattersley, C.; Molins, B.; Buckley, C.; Povey, C.; Pellicano, E.',
    title: 'Which terms should be used to describe autism? Perspectives from the UK autism community',
    year: 2016,
    doi: '10.1177/1362361315588200',
    url: 'https://doi.org/10.1177/1362361315588200',
    types: ['equidade', 'conceitual'],
    population: 'Comunidade autista do Reino Unido.',
    limitations: 'Preferências de linguagem variam entre países e pessoas.',
    relation: 'Linguagem não estigmatizante em toda a interface.',
  },
  {
    id: 'cosmin-2010',
    citation: 'Mokkink, L. B.; Terwee, C. B.; Patrick, D. L. et al.',
    title: 'The COSMIN checklist for assessing the methodological quality of studies on measurement properties of health status measurement instruments',
    year: 2010,
    doi: '10.1007/s11136-010-9606-8',
    url: 'https://doi.org/10.1007/s11136-010-9606-8',
    types: ['validade', 'confiabilidade'],
    population: 'Instrumentos de medida em saúde.',
    limitations: 'Checklist metodológico; não define pontos de corte.',
    relation: 'Estrutura do repositório de evidências e do plano de validação.',
  },
  {
    id: 'standards-2014',
    citation: 'AERA; APA; NCME',
    title: 'Standards for Educational and Psychological Testing',
    year: 2014,
    url: 'https://www.testingstandards.net/',
    types: ['validade', 'confiabilidade', 'equidade'],
    population: 'Testagem educacional e psicológica.',
    limitations: 'Contexto norte-americano.',
    relation: 'Fontes de evidência de validade, equidade e documentação.',
  },
  {
    id: 'cfp-31-2022',
    citation: 'Conselho Federal de Psicologia',
    title: 'Resolução CFP nº 31/2022 — diretrizes para a avaliação psicológica',
    year: 2022,
    url: 'https://site.cfp.org.br/nova-resolucao-do-cfp-destaca-diretrizes-para-a-avaliacao-psicologica/',
    types: ['norma'],
    population: 'Profissionais de psicologia no Brasil.',
    limitations: 'Verificar vigência e normas complementares antes do lançamento.',
    relation: 'O sistema não emite documento psicológico nem substitui avaliação psicológica.',
  },
  {
    id: 'satepsi',
    citation: 'Conselho Federal de Psicologia — SATEPSI',
    title: 'Sistema de Avaliação de Testes Psicológicos — legislação',
    year: 2026,
    url: 'https://satepsi.cfp.org.br/legislacao.cfm',
    types: ['norma'],
    population: 'Testes psicológicos de uso profissional.',
    limitations: 'Status dos testes muda; consultar antes de cada uso profissional.',
    relation: 'Nenhum teste privativo é aplicado; módulos próprios ficam como pesquisa.',
  },
  {
    id: 'cfp-etica',
    citation: 'Conselho Federal de Psicologia',
    title: 'Código de Ética Profissional do Psicólogo (Resolução CFP nº 010/2005)',
    year: 2005,
    url: 'https://site.cfp.org.br/wp-content/uploads/2012/07/codigo-de-etica-psicologia.pdf',
    types: ['norma'],
    population: 'Profissionais de psicologia no Brasil.',
    limitations: 'Verificar atualizações.',
    relation: 'Sigilo, finalidade e limites do compartilhamento com profissionais.',
  },
  {
    id: 'lgpd',
    citation: 'Brasil',
    title: 'Lei nº 13.709, de 14 de agosto de 2018 — Lei Geral de Proteção de Dados Pessoais (LGPD)',
    year: 2018,
    url: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm',
    types: ['protecao-dados', 'norma'],
    population: 'Tratamento de dados pessoais no Brasil.',
    limitations: 'Dados de saúde são sensíveis; exige análise jurídica do caso concreto.',
    relation: 'Consentimentos separados, direitos do titular, minimização e registro de acessos.',
  },
  {
    id: 'cns-466',
    citation: 'Conselho Nacional de Saúde',
    title: 'Resolução nº 466, de 12 de dezembro de 2012 — pesquisas envolvendo seres humanos',
    year: 2012,
    url: 'https://conselho.saude.gov.br/resolucoes/2012/Reso466.pdf',
    types: ['etica-pesquisa', 'norma'],
    population: 'Pesquisa com seres humanos no Brasil.',
    limitations: 'Verificar normas complementares do sistema CEP/CONEP.',
    relation: 'Coleta para pesquisa só após aprovação ética do protocolo.',
  },
  {
    id: 'cns-510',
    citation: 'Conselho Nacional de Saúde',
    title: 'Resolução nº 510, de 7 de abril de 2016 — pesquisas em Ciências Humanas e Sociais',
    year: 2016,
    url: 'https://conselho.saude.gov.br/resolucoes/2016/Reso510.pdf',
    types: ['etica-pesquisa', 'norma'],
    population: 'Pesquisa em Ciências Humanas e Sociais no Brasil.',
    limitations: 'Aplicabilidade depende do desenho do estudo.',
    relation: 'Registro de consentimento e riscos mínimos em questionários.',
  },
  {
    id: 'wcag22',
    citation: 'World Wide Web Consortium (W3C)',
    title: 'Web Content Accessibility Guidelines (WCAG) 2.2',
    year: 2023,
    url: 'https://www.w3.org/TR/WCAG22/',
    types: ['acessibilidade', 'norma'],
    population: 'Conteúdo web.',
    limitations: 'Conformidade técnica não substitui testes com pessoas.',
    relation: 'Referência AA para contraste, teclado, foco, leitores de tela e movimento.',
  },
]

export const REFERENCE_BY_ID = Object.fromEntries(REFERENCES.map((r) => [r.id, r])) as Record<string, Reference>

export const REFERENCE_TYPE_LABEL: Record<ReferenceType, string> = {
  norma: 'Norma',
  diretriz: 'Diretriz clínica',
  revisao: 'Revisão sistemática',
  validade: 'Estudo de validade',
  confiabilidade: 'Confiabilidade',
  acessibilidade: 'Acessibilidade',
  equidade: 'Equidade',
  'protecao-dados': 'Proteção de dados',
  'etica-pesquisa': 'Ética em pesquisa',
  conceitual: 'Base conceitual',
}

export const shortCitation = (r: Reference) => `${r.citation.split(';')[0]!.split(',')[0]} · ${r.year}`
